#pragma once

#define FFE_KEY_UNKNOWN					0

#define FFE_KEY_A						4
#define FFE_KEY_B						5
#define FFE_KEY_C						6
#define FFE_KEY_D						7
#define FFE_KEY_E						8
#define FFE_KEY_F						9
#define FFE_KEY_G						10
#define FFE_KEY_H						11
#define FFE_KEY_I						12
#define FFE_KEY_J						13
#define FFE_KEY_K						14
#define FFE_KEY_L						15
#define FFE_KEY_M						16
#define FFE_KEY_N						17
#define FFE_KEY_O						18
#define FFE_KEY_P						19
#define FFE_KEY_Q						20
#define FFE_KEY_R						21
#define FFE_KEY_S						22
#define FFE_KEY_T						23
#define FFE_KEY_U						24
#define FFE_KEY_V						25
#define FFE_KEY_W						26
#define FFE_KEY_X						27
#define FFE_KEY_Y						28
#define FFE_KEY_Z						29

#define FFE_KEY_1						30
#define FFE_KEY_2						31
#define FFE_KEY_3						32
#define FFE_KEY_4						33
#define FFE_KEY_5						34
#define FFE_KEY_6						35
#define FFE_KEY_7						36
#define FFE_KEY_8						37
#define FFE_KEY_9						38
#define FFE_KEY_0						39

#define FFE_KEY_RETURN					40
#define FFE_KEY_ESCAPE					41
#define FFE_KEY_BACKSPACE				42
#define FFE_KEY_TAB						43
#define FFE_KEY_SPACE					44

#define FFE_KEY_MINUS					45
#define FFE_KEY_EQUALS					46
#define FFE_KEY_LEFTBRACKET				47
#define FFE_KEY_RIGHTBRACKET			48
#define FFE_KEY_BACKSLASH				49
#define FFE_KEY_NONUSHASH				50
#define FFE_KEY_SEMICOLON				51
#define FFE_KEY_APOSTROPHE				52
#define FFE_KEY_GRAVE					53
#define FFE_KEY_COMMA					54
#define FFE_KEY_PERIOD					55
#define FFE_KEY_SLASH					56

#define FFE_KEY_CAPSLOCK				57

#define FFE_KEY_F1						58
#define FFE_KEY_F2						59
#define FFE_KEY_F3						60
#define FFE_KEY_F4						61
#define FFE_KEY_F5						62
#define FFE_KEY_F6						63
#define FFE_KEY_F7						64
#define FFE_KEY_F8						65
#define FFE_KEY_F9						66
#define FFE_KEY_F10						67
#define FFE_KEY_F11						68
#define FFE_KEY_F12						69

#define FFE_KEY_PRINTSCREEN				70
#define FFE_KEY_SCROLLLOCK				71
#define FFE_KEY_PAUSE					72
#define FFE_KEY_INSERT					73

#define FFE_KEY_HOME					74
#define FFE_KEY_PAGEUP					75
#define FFE_KEY_DELETE					76
#define FFE_KEY_END						77
#define FFE_KEY_PAGEDOWN				78
#define FFE_KEY_RIGHT					79
#define FFE_KEY_LEFT					80
#define FFE_KEY_DOWN					81
#define FFE_KEY_UP						82

#define FFE_KEY_NUMLOCKCLEAR			83 

#define FFE_KEY_KP_DIVIDE				84
#define FFE_KEY_KP_MULTIPLY				85
#define FFE_KEY_KP_MINUS				86
#define FFE_KEY_KP_PLUS					87
#define FFE_KEY_KP_ENTER				88
#define FFE_KEY_KP_1					89
#define FFE_KEY_KP_2					90
#define FFE_KEY_KP_3					91
#define FFE_KEY_KP_4					92
#define FFE_KEY_KP_5					93
#define FFE_KEY_KP_6					94
#define FFE_KEY_KP_7					95
#define FFE_KEY_KP_8					96
#define FFE_KEY_KP_9					97
#define FFE_KEY_KP_0					98
#define FFE_KEY_KP_PERIOD				99

#define FFE_KEY_NONUSBACKSLASH			100 
#define FFE_KEY_APPLICATION				101
#define FFE_KEY_POWER					102 
#define FFE_KEY_KP_EQUALS				103
#define FFE_KEY_F13						104
#define FFE_KEY_F14						105
#define FFE_KEY_F15						106
#define FFE_KEY_F16						107
#define FFE_KEY_F17						108
#define FFE_KEY_F18						109
#define FFE_KEY_F19						110
#define FFE_KEY_F20						111
#define FFE_KEY_F21						112
#define FFE_KEY_F22						113
#define FFE_KEY_F23						114
#define FFE_KEY_F24						115
#define FFE_KEY_EXECUTE					116
#define FFE_KEY_HELP					117
#define FFE_KEY_MENU					118
#define FFE_KEY_SELECT					119
#define FFE_KEY_STOP					120
#define FFE_KEY_AGAIN					121
#define FFE_KEY_UNDO					122
#define FFE_KEY_CUT						123
#define FFE_KEY_COPY					124
#define FFE_KEY_PASTE					125
#define FFE_KEY_FIND					126
#define FFE_KEY_MUTE					127
#define FFE_KEY_VOLUMEUP				128
#define FFE_KEY_VOLUMEDOWN				129

#define FFE_KEY_KP_COMMA				133
#define FFE_KEY_KP_EQUALSAS400			134

#define FFE_KEY_INTERNATIONAL1			135
#define FFE_KEY_INTERNATIONAL2			136
#define FFE_KEY_INTERNATIONAL3			137
#define FFE_KEY_INTERNATIONAL4			138
#define FFE_KEY_INTERNATIONAL5			139
#define FFE_KEY_INTERNATIONAL6			140
#define FFE_KEY_INTERNATIONAL7			141
#define FFE_KEY_INTERNATIONAL8			142
#define FFE_KEY_INTERNATIONAL9			143
#define FFE_KEY_LANG1					144 
#define FFE_KEY_LANG2					145 
#define FFE_KEY_LANG3					146 
#define FFE_KEY_LANG4					147 
#define FFE_KEY_LANG5					148 
#define FFE_KEY_LANG6					149 
#define FFE_KEY_LANG7					150 
#define FFE_KEY_LANG8					151 
#define FFE_KEY_LANG9					152 

#define FFE_KEY_ALTERASE				153
#define FFE_KEY_SYSREQ					154
#define FFE_KEY_CANCEL					155
#define FFE_KEY_CLEAR					156
#define FFE_KEY_PRIOR					157
#define FFE_KEY_RETURN2					158
#define FFE_KEY_SEPARATOR				159
#define FFE_KEY_OUT						160
#define FFE_KEY_OPER					161
#define FFE_KEY_CLEARAGAIN				162
#define FFE_KEY_CRSEL					163
#define FFE_KEY_EXSEL					164

#define FFE_KEY_KP_00					176
#define FFE_KEY_KP_000					177
#define FFE_KEY_THOUSANDSSEPARATOR		178
#define FFE_KEY_DECIMALSEPARATOR		179
#define FFE_KEY_CURRENCYUNIT			180
#define FFE_KEY_CURRENCYSUBUNIT			181
#define FFE_KEY_KP_LEFTPAREN			182
#define FFE_KEY_KP_RIGHTPAREN			183
#define FFE_KEY_KP_LEFTBRACE			184
#define FFE_KEY_KP_RIGHTBRACE			185
#define FFE_KEY_KP_TAB					186
#define FFE_KEY_KP_BACKSPACE			187
#define FFE_KEY_KP_A					188
#define FFE_KEY_KP_B					189
#define FFE_KEY_KP_C					190
#define FFE_KEY_KP_D					191
#define FFE_KEY_KP_E					192
#define FFE_KEY_KP_F					193
#define FFE_KEY_KP_XOR					194
#define FFE_KEY_KP_POWER				195
#define FFE_KEY_KP_PERCENT				196
#define FFE_KEY_KP_LESS					197
#define FFE_KEY_KP_GREATER				198
#define FFE_KEY_KP_AMPERSAND			199
#define FFE_KEY_KP_DBLAMPERSAND			200
#define FFE_KEY_KP_VERTICALBAR			201
#define FFE_KEY_KP_DBLVERTICALBAR		202
#define FFE_KEY_KP_COLON				203
#define FFE_KEY_KP_HASH					204
#define FFE_KEY_KP_SPACE				205
#define FFE_KEY_KP_AT					206
#define FFE_KEY_KP_EXCLAM				207
#define FFE_KEY_KP_MEMSTORE				208
#define FFE_KEY_KP_MEMRECALL			209
#define FFE_KEY_KP_MEMCLEAR				210
#define FFE_KEY_KP_MEMADD				211
#define FFE_KEY_KP_MEMSUBTRACT			212
#define FFE_KEY_KP_MEMMULTIPLY			213
#define FFE_KEY_KP_MEMDIVIDE			214
#define FFE_KEY_KP_PLUSMINUS			215
#define FFE_KEY_KP_CLEAR				216
#define FFE_KEY_KP_CLEARENTRY			217
#define FFE_KEY_KP_BINARY				218
#define FFE_KEY_KP_OCTAL				219
#define FFE_KEY_KP_DECIMAL				220
#define FFE_KEY_KP_HEXADECIMAL			221

#define FFE_KEY_LCTRL					224
#define FFE_KEY_LSHIFT					225
#define FFE_KEY_LALT					226
#define FFE_KEY_LGUI					227
#define FFE_KEY_RCTRL					228
#define FFE_KEY_RSHIFT					229
#define FFE_KEY_RALT					230
#define FFE_KEY_RGUI					231

#define FFE_KEY_MODE					257

#define FFE_KEY_AUDIONEXT				258
#define FFE_KEY_AUDIOPREV				259
#define FFE_KEY_AUDIOSTOP				260
#define FFE_KEY_AUDIOPLAY				261
#define FFE_KEY_AUDIOMUTE				262
#define FFE_KEY_MEDIASELECT				263
#define FFE_KEY_WWW						264
#define FFE_KEY_MAIL					265
#define FFE_KEY_CALCULATOR				266
#define FFE_KEY_COMPUTER				267
#define FFE_KEY_AC_SEARCH				268
#define FFE_KEY_AC_HOME					269
#define FFE_KEY_AC_BACK					270
#define FFE_KEY_AC_FORWARD				271
#define FFE_KEY_AC_STOP					272
#define FFE_KEY_AC_REFRESH				273
#define FFE_KEY_AC_BOOKMARKS			274


#define FFE_KEY_BRIGHTNESSDOWN			275
#define FFE_KEY_BRIGHTNESSUP			276
#define FFE_KEY_DISPLAYSWITCH			277
#define FFE_KEY_KBDILLUMTOGGLE			278
#define FFE_KEY_KBDILLUMDOWN			279
#define FFE_KEY_KBDILLUMUP				280
#define FFE_KEY_EJECT					281
#define FFE_KEY_SLEEP					282

#define FFE_KEY_APP1					283
#define FFE_KEY_APP2					284

#define FFE_KEY_AUDIOREWIND				285
#define FFE_KEY_AUDIOFASTFORWARD		286