#pragma once

#define FFE_MOUSE_BUTTON(X)       (1 << ((X)-1))
#define FFE_MOUSE_BUTTON_LEFT     1
#define FFE_MOUSE_BUTTON_MIDDLE   2
#define FFE_MOUSE_BUTTON_RIGHT    3
#define FFE_MOUSE_BUTTON_X1       4
#define FFE_MOUSE_BUTTON_X2       5
#define FFE_MOUSE_BUTTON_LMASK    FFE_MOUSE_BUTTON(FFE_MOUSE_BUTTON_LEFT)
#define FFE_MOUSE_BUTTON_MMASK    FFE_MOUSE_BUTTON(FFE_MOUSE_BUTTON_MIDDLE)
#define FFE_MOUSE_BUTTON_RMASK    FFE_MOUSE_BUTTON(FFE_MOUSE_BUTTON_RIGHT)
#define FFE_MOUSE_BUTTON_X1MASK   FFE_MOUSE_BUTTON(FFE_MOUSE_BUTTON_X1)
#define FFE_MOUSE_BUTTON_X2MASK   FFE_MOUSE_BUTTON(FFE_MOUSE_BUTTON_X2)